# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: caaea594d7b8992e8b7b7a77ab65919e72c1ee86f6a46d70fa089209bc445a32e8b85ad1ff5637d0a105a1b9169a19edd1a0dc4f4b5ae9cd6aa1a1c5fad08e2b
  access_key_id: AKIAJSIGZCIYNFWJB6ZQ
  secret_access_key: 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
  s3_bucket_name: goodmeet

test:
  secret_key_base: 0566608f3361d1832956e3118405d5eb5a37980ccf0e64c514f9bd46eadbb6ed78c4577e3313a792430120e6f7e652b89578fc955f338f08e6556a63f02068b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key: <%= ENV["SECRET_KEY"] %>
  publishable_key: <%= ENV["PUBLISHABLE_KEY"] %>
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  s3_bucket_name: <%= ENV["S3_BUCKET_NAME"]%>
